### PR TITLE
Switching the error info from an array to a hash.

### PR DESCRIPTION
**Pull request by DavidEBest**

### CODE REVIEW

**Comment by mbland** [comment]
Looks good, but want one of @annalee, @ertzeid, and/or @ccostino to review and merge.

**Comment by ccostino** [comment]
The change itself looks fine to me, but what is the impetus behind it?  It seemed like before it was possible to capture multiple errors but now we're only capture one per repo with this change (with various pieces of metadata related to it).  This is just me not fully understanding the context and if I were to hazard a guess it looks like this is simplifying things a bit, but I just wanted to make sure I understand correctly.

**Comment by DavidEBest** [comment]
@ccostino The goal of this is to simplify the structure of the output from:

```
[
  { projname1 => projErr},
  { projname2 => projErr},
  { projname3 => projErr}
]
```

to:

```
{
  projname1 => projErr,
  projname2 => projErr,
  projname3 => projErr
}
```

The errors caught here are of the terminal variety (i.e. the file isn't valid yaml) so there should only ever be a single error in a repo.

Arguably, that line could be 

```
result['errors'][repo.full_name] = [err.message]
```

to better support multiple errors.

**Comment by ccostino** [comment]
@DavidEBest:  That's what I thought, but I just wanted to make sure, thank you for clarifying!  This is fine for me, I'm happy to merge if all is good to go.

**Pull request merged**
