### PR TITLE
Rename blog -> blog_tag and update metadata. connects #46

### PR DESCRIPTION
**Pull request by ertzeid**

### CODE REVIEW

**Comment by ccostino** [comment]
Looks good to me!  Is this the only piece necessary on this side of things?  According to #46 it seems that way.

**Comment by mbland** [comment]
I'm thinking two things:
1. This should probably be applied to `lib/schema.json` in `18F/about-yml-validator`, as we'll eventually update the gem to depend on the npm for the schema.
2. Looks like @mtorres253 wants to coordinate with the 18F/Dashboard team on the migration, so we might want to hold off on merging 'til then.

**Comment by mtorres253** [comment]
Yes, I'm going to talk to Greg today, and I'm going to send a message to our early adopters to let them know to expect the change. Will update here

**Comment by ccostino** [comment]
https://github.com/18F/about-yml-validator/issues/5 created to account for the `18F/about-yml-validator` update for parity.

PR with changes:  https://github.com/18F/about-yml-validator/pull/6

**Comment by ccostino** [comment]
Additional change looks fine!  I created another `about-yml-validator` PR to account for it as well: https://github.com/18F/about-yml-validator/pull/8

I'll keep that one open until this is merged.

**Pull request merged**
