### PR TITLE
Typo fix: 'MWhat' --> 'What'

### PR DESCRIPTION
**Pull request by fureigh**

### CODE REVIEW

**Comment by mbland** [comment]
@fureigh Mind fixing this in `lib/ABOUT_yml/schema.json, too?

**Comment by mbland** [comment]
Gah. So much for a fast, elegant edit on my phone before pulling out of the Metro station and losing signal.

**Comment by wslack** [comment]
Ask @mbland asked ^^

**Comment by fureigh** [comment]
Wouldn't have minded but didn't check work email this weekend. Thanks for the catch-fix-merge, @mbland!

**Pull request merged**
