### PR TITLE
Update about_yml.gemspec

### PR DESCRIPTION
**Pull request by melodykramer**
remove alison as owner because she is no longer at 18F

### CODE REVIEW

**Comment by mbland** [comment]
:cry:

I'd rather @arowla chime in, and merge this herself. Then again, she _is_ one of the authors, and this code is public domain. Should we remove people just because they leave 18F? Does wg-opensource have any guidance? (I'll ask in a bit if no one beats me to it.)

This also raises the question of who we should add, or more to the point, if there's an organizational account we should add.

**Comment by arowla** [comment]
Not sure what you found out, @mbland, if anything, but it would be nice to retain authorship credit. Not inclined to merge this change, at least until there is more clarity.

**Comment by mbland** [comment]
Sadly, I let this sit 'til now, having blocked out the world to work on 18F/unit-testing-node (the full draft of which I'll start publishing today). But, I've just raised the question to the Opensource Working Group.

**Comment by gboone** [comment]
I think the person who wrote the code should be listed as an author unless they ask to be removed in some way. We don't remove authors from blog posts even though we take their picture off 18f.gsa.gov/team/. If we're going to keep maintaining the project we should make sure there's someone at 18F who can answer questions, respond to pull requests, issues, etc. and that they also be listed as authors. Someone on Slack, @stvnrlly, I think, suggested offering a team email address, instead of individuals, for people to email with questions or patches (do people still email patch files?) or other concerns. 

That seems like a good approach to me.

**Comment by mtorres253** [comment]
I think @gboone sums it up nicely. Going to close without merging for now.

**Pull request closed without merging**
